version: '2'
services:

  devcontainer:
    build:
      context: .
      args:
        DBT_VERSION: 1.0.0
    volumes:
      - .:/workspaces/jaffle_shop_dbtvault/
    ports:
      - "8080:8080"

  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
