name: Continuous Integration Tests

on:
  pull_request:
    branches: [ main ]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true  

jobs:
  ci:
    name: Continuous Integration Tests
    timeout-minutes: 30
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: wait for services to start up
        run: sleep 10
      - name: dbt version
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt --version
      - name: dbt debug
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt debug          
      - name: dbt deps
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt deps
      - name: dbt init_source_data 
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt sedd
      - name: dbt build
        uses: kzzzr/mybi-dbt-action@v4
        with:
          command: dbt build --full-refresh
